### ISSUE TITLE
Setup a Hosted Demo

### ISSUE THREAD

**Issue by milesfrain** [jonasbuntinx/purescript-react-realworld#1]
We should create a hosted demo for inclusion in the 2021 Frontend Framework Comparison. ([2020 post](https://medium.com/dailyjs/a-realworld-comparison-of-front-end-frameworks-2020-4e50655fe4c1)).

@wryk, would you like to help with this too while you're tackling https://github.com/thomashoneyman/purescript-halogen-realworld/issues/21 ?

**Comment by wryk** [comment]
With pleasure, but I will wait for feedback before proposing an equivalent solution here.

**Comment by jonasbuntinx** [comment]
By all means 😄

**Comment by jonasbuntinx** [comment]
I took the liberty of setting up a hosted demo myself. You can see it here: 

https://purescript-react-realworld.netlify.app

I'll update the README.md later.

**Comment by milesfrain** [comment]
Nice! Here's a preview of the results to expect in the 2021 comparison:




Bundle: **82 KB** compressed, 495 KB uncompressed
- Halogen: 112 KB compressed, 584 KB uncompressed
- Median: 99.8 KB compressed

Lighthouse performance: **70**
- Median: 91

Lines of code: **3140**
- Median 2050
```
➜  react-realworld git:(master) cloc src                                
      49 text files.
      49 unique files.                              
       0 files ignored.

github.com/AlDanial/cloc v 1.86  T=0.04 s (1206.5 files/s, 85095.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
PureScript                      45            287             16           3094
JavaScript                       4             13              0             46
-------------------------------------------------------------------------------
SUM:                            49            300             16           3140
-------------------------------------------------------------------------------
```
