### ISSUE TITLE
Can we drop `unsafePerformEffect` from `Routing`?

### ISSUE THREAD

**Issue by paluh** [jonasbuntinx/purescript-react-realworld#2]
Hi,

I'm learning a lot by reading your example application :-) Thanks a lot for building it!

I'm not sure if this is a real issue but I can imagine that when I want to render some pieces of the app on the server the `unsafePerformEffect` from [Conduit.Env.Routing](https://github.com/jonasbuntinx/purescript-react-realworld/blob/master/src/Conduit/Env/Routing.purs#L21) which triggers some DOM related actions could possibly cause a problem. Probably on the server we want to use "mock" of the `PushStateInterface` or something to render the initial JSX. What do you think?

Do you think that it is feasible to move `navigate` and `redirect` to the current environment so we end up with has something like this:

```purescript
type Env = { ..., routing :: { signal :: RoutingSignal, navigate :: ..., redirect :: ... }}
```

**Comment by jonasbuntinx** [comment]
I create a PR #3 that removes the `unsafePerformEffect`. Is this what you had in mind?

**Comment by paluh** [comment]
Yeah, I thought about this "minor" change - something like you have done here: https://github.com/jonasbuntinx/purescript-react-realworld/pull/3/files#diff-04a96ecd97a6fcd5b3513d19ad38f643R15

Do the whole PR is a consequence of this change? I thought that it would be a minor modification and that it would not have such a spread impact. Do you think that it is acceptable to make such a significant modification to the API to have it more SSR safe?

**Comment by jonasbuntinx** [comment]
I'm just seeing how far I can take this. 

I've wanted to do a AppM like the the Halogen example, and this is a good excuse.
