### ISSUE TITLE
Example hook based component using `useHalo`?

### ISSUE THREAD

**Issue by jetaggart** [jonasbuntinx/purescript-react-realworld#20]
Hey, thank you for putting this together, this is answering a ton of questions I have on how to structure things, especially the `AppM`. 

One thing I'm struggling with is how to use the `useHalo` hook? And more generally, how could I convert one of the more complex examples, such as a `Page`, into a component only using hooks?

Thank you in advance, sorry is this is the wrong forum to ask!

**Comment by jonasbuntinx** [comment]
Hi,

Thanks, I'm glad you find this example useful.

I'm not sure what your question is. 
You are asking how to write a component, like a page, with only hooks?
But they already are using hooks, what non-hook thing are you referring too?

Concerning `useHalo`, you can look at it's repo to see how it works and how to use it:
https://github.com/robertdp/purescript-react-halo

**Comment by jetaggart** [comment]
Sorry, I'm relatively new to all of this, so apologies for any confusion. I really appreciate the help!

I'm confused on how I could use a custom hook within the Halo structure. For example, using a library such as this: https://react-hook-form.com/. I don't see how I'd use `useEffectOnce` or `useForm` for example. Would I just do it within the `render` function?

**Comment by jonasbuntinx** [comment]
This might be useful:

https://github.com/robertdp/purescript-react-halo/issues/9#issuecomment-787005206

**Comment by jetaggart** [comment]
Perfect, thank you!
