### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [jonasbuntinx/purescript-react-realworld#24]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by jonasbuntinx** [comment]
Hi @geromegrignon 

Thanks for the heads up. I have updated the API url in https://github.com/jonasbuntinx/purescript-react-realworld/commit/d23a0616f511e3b923f1a7a003b49bd4c2be15ae

Cheers

**Comment by geromegrignon** [comment]
Hey @jonasbuntinx, thanks for the quick update!
