### ISSUE TITLE
Using lookupEnv and dotenv for configuration

### ISSUE THREAD

**Issue by paluh** [jonasbuntinx/purescript-react-realworld#4]
What do you think about using [`lookupEnv`](https://pursuit.purescript.org/packages/purescript-node-process/7.0.0/docs/Node.Process#v:lookupEnv) and adding [_purescript-dotenv_](https://github.com/nsaunders/purescript-dotenv) dependency to this project so we can have a bit more elegant (no direct FFI) way of handling configuration? Is it worth it? Should I provide a PR?

**Comment by robertdp** [comment]
That would work for server-side applications, but not with this projects bundling approach. Node `process.env` values are encoded at bundle time by Parcel, and can't be read from the environment or from a dotfile by the application because these don't exist in the browser.

**Comment by paluh** [comment]
Oh sorry. Stupid me ;-)

**Comment by paluh** [comment]
P.S.
@robertdp I was somewhat mislead by the code from [`Config.js`](https://github.com/jonasbuntinx/purescript-react-realworld/blob/master/src/Conduit/Config.js). Is `process` a thing in the browser environment? I should probably just check where it is used ;-)

**Comment by robertdp** [comment]
`process` is a magic global variable that is provided by Node and doesn't exist in the browser. So the packaging/bundling tools have access to it at build/bundle time. After that we're out of luck.

In Parcels case it searches the JS it is bundling for `process.env.SOME_VAR` and replaces that with the string-encoded value from the environment. It also automatically loads dotenv config files and gives those values higher priority than values from the Node environment.

`Config.js` is just a convenient way of injecting these values so we can access them in the browser.
