### ISSUE TITLE
A question about initial value of the routing signal

### ISSUE THREAD

**Issue by paluh** [jonasbuntinx/purescript-react-realworld#5]
Sorry for bothering you with another possibly naive question but from the code review I'm not able to grasp the idea how important is the initialization of the routing signal.
I mean [currently (even on the branch)]( https://github.com/jonasbuntinx/purescript-react-realworld/blob/routing-env/src/Conduit/Env/Routing.purs#L18) the routing signal is initialized with `Home` value but it seems that this doesn't really impact the app behavior - it displays correct content for an initial url.
Could you please give me a hint how is it possible that initial app routing works correctly with this predefined constant `Home` route and why we don't have to parse the url during signal initialization?

**Comment by paluh** [comment]
I just want to propose a separation of your really nice routing hook into a small lib, but I'm not sure if we should add initial parsing of URL somewhere here or not (this is nearly just a copy+paste of your routing pieces into a single place):

```purescript
module React.Basic.Routing.Duplex where

import Prelude

import Data.Maybe (Maybe(..))
import Data.Tuple.Nested (type (/\), (/\))
import Effect (Effect)
import Foreign.NullOrUndefined (undefined)
import React.Basic.Hooks as React
import Routing.Duplex (RouteDuplex', parse, print)
import Routing.PushState as PushState
import Wire.Event as Event
import Wire.React (UseAtom, useAtomValue)
import Wire.React.Class (modify)
import Wire.React.Pure (Pure, create) as Pure

type RoutingEnv route
  = { signal :: RoutingSignal (Maybe route /\ route)
    , navigate :: route -> Effect Unit
    , redirect :: route -> Effect Unit
    }

type RoutingSignal route = Pure.Pure route

create :: forall route. route -> Effect (RoutingSignal (Maybe route /\ route))
create default = Pure.create (Nothing /\ default)

mkRoutingManager ::
  forall route.
  route ->
  RouteDuplex' route ->
  Effect (RoutingEnv route /\ (React.JSX -> React.JSX))
mkRoutingManager default duplex = do
  interface <- PushState.makeInterface
  routingSignal <- create default
  component <-
    React.component "RoutingManager" \content -> React.do
      React.useEffectOnce do
        Event.subscribe (onPushState interface duplex) \routes -> do
          modify routingSignal $ const $ routes
      pure content
  pure
    $ { signal: routingSignal
      , navigate: navigate interface
      , redirect: redirect interface
      }
    /\ component
  where
  onPushState interface matcher =
    Event.makeEvent \k ->
      PushState.matchesWith (parse matcher) (\old new -> k (old /\ new)) interface

  navigate interface = interface.pushState undefined <<< print duplex

  redirect interface = interface.replaceState undefined <<< print duplex

useRoute :: forall route. RoutingSignal (Maybe route /\ route) -> React.Hook (UseAtom (Maybe route /\ route)) (Maybe route /\ route)
useRoute routingSignal = useAtomValue routingSignal
```

I'm not sure if we want to preserve the `old /\ new` but it seems that it could be useful in scenarios like alerting etc.

**Comment by paluh** [comment]
P.S.

If you decide to publish it as a separate lib it would be nice to also add some info to the docs that unmatched urls are ignored. Of course I can try to help to write this using my buggy English ;-)

**Comment by paluh** [comment]
I think that we can also add to `RoutingEnv` something like `print :: route -> String` which will complement `navigate` and gives value for `href` attr. What do you think?

**Comment by jonasbuntinx** [comment]
> Could you please give me a hint how is it possible that initial app routing works correctly with this predefined constant `Home` route and why we don't have to parse the url during signal initialization?

The `Home` does show up for a split second, so I added a parse when loading the initial route:
https://github.com/jonasbuntinx/purescript-react-realworld/blob/0bb4a5e371e750d78f4b3dd0924236a678029895/src/Conduit/Env/Routing.purs#L35

**Comment by jonasbuntinx** [comment]
> If you decide to publish it as a separate lib it would be nice to also add some info to the docs that unmatched urls are ignored. Of course I can try to help to write this using my buggy English ;-)

No plans to do that. I feel the current routing component is very much tied to this implementation.

**Comment by jonasbuntinx** [comment]
> I think that we can also add to `RoutingEnv` something like `print :: route -> String` which will complement `navigate` and gives value for `href` attr. What do you think?

The `IsRoute` class solves that.

**Comment by paluh** [comment]
> No plans to do that. I feel the current routing component is very much tied to this implementation.

That is interesting. I think that it is quite general - I want to use it in two projects right away :-P  Would you mind if I separate the above module and give you a credit for it in the README?

**Comment by jonasbuntinx** [comment]
> That is interesting. I think that it is quite general - I want to use it in two projects right away :-P Would you mind if I separate the above module and give you a credit for it in the README?

I think for now it would be better just to copy this component into whatever project you want to use it. The current component is tiny and only support minimal features of a router (i.e. we don't preserve the previous route).
